fix: JOIN-31701 update pubsub library to publish and consume avro encoded messages
join-com/pubsub pull request #66
Opened 2023-05-08 07:15 UTC by eugeneswave

2023-05-08 08:42 UTC, ddadonJoin commented on packages/pubsub/src/Subscriber.ts
> +          // and if we add async everywhere we will have to change current library API
Maybe explain that this will only happen when we migrate from JSON to Avro and that no message will be lost

2023-05-08 08:45 UTC, ddadonJoin commented on packages/pubsub/src/TopicHandler.ts
> +    // const schemaName = topic.metadata?.schemaSettings?.schema
You can remove this

2023-05-08 08:46 UTC, ddadonJoin commented on packages/pubsub/src/TopicHandler.ts
> +  protected async getTopicType() {
Can you put an explicit return type? Also This should have been raised by the linter so could you also update the linter?

2023-05-08 08:47 UTC, ddadonJoin commented on packages/pubsub/src/TopicHandler.ts
> +    const schemaName = metadata?.[0].schemaSettings?.schema
What happens if `[0]` return undefined? This could raise an exception no?

2023-05-08 08:47 UTC, ddadonJoin commented on packages/pubsub/src/TopicHandler.ts
> +import * as avro from 'avsc'
We should avoid star import I think :)

2023-05-08 08:49 UTC, ddadonJoin requested changes
Good start :)

2023-05-08 08:49 UTC, ddadonJoin requested changes
Good start :)

2023-05-08 08:49 UTC, ddadonJoin requested changes
Good start :)

2023-05-08 09:11 UTC, kirpichenko commented on packages/pubsub/src/Publisher.ts
> +        this.avroType = await this.getTopicType()
shouldn't the schema change happen together with deployment?

2023-05-08 09:11 UTC, kirpichenko commented on packages/pubsub/src/Publisher.ts
> +        this.avroType = await this.getTopicType()
maybe we can continue publishing as a json if the schema is not set, additionally pass the schema/type via attributes to the client and let the client decide how to parse the message?

2023-05-08 09:11 UTC, kirpichenko commented on packages/pubsub/src/Publisher.ts
> +    await this.publishWithLog({ data: buffer })
the logger seems like will print a buffer instead of the published message

2023-05-08 10:15 UTC, eugeneswave commented on packages/pubsub/src/Publisher.ts
> +        this.avroType = await this.getTopicType()
> shouldn't the schema change happen together with deployment?

Yes, as we are already managing topics in the code, so we will assign schema to the topic in the code, and we will have schema update as a part of deployment (probably gcloud calls inside docker image or terraform if we can manage it). 

The problem is, we can not completely stop the server, and in this case some pods will be still not updated, and some pods will be new.

So new pods will work fine, but old pods will publish the data in JSON, so they will receive error, then they will get new schema from the topic, and send the data with the schema, and that's why we have this try-catch here

2023-05-08 10:18 UTC, eugeneswave commented on packages/pubsub/src/Publisher.ts
> +        this.avroType = await this.getTopicType()
> maybe we can continue publishing as a json if the schema is not set, additionally pass the schema/type via attributes to the client and let the client decide how to parse the message?

Our end goal is to have avro enabled on the topic, to use pubsub subscriber for BigQuery, and I don't see how additional field in json will help us here. Because for now we will need to handle 2 cases JSON or AVRO, with additional field, it will be 3 cases, and I don't see how it helps us.

2023-05-10 08:33 UTC, ddadonJoin requested changes

2023-05-10 08:33 UTC, ddadonJoin commented on packages/pubsub/src/DataParser.ts
> +        obj[key] = undefined;
Our code style does not use semicolons, the linter should have catch it though, can you check why?

2023-05-10 08:33 UTC, ddadonJoin commented on packages/pubsub/src/Publisher.ts
> +        this.topic = this.client.topic(this.topic.name)
Why do we need to re-assign topic here?

2023-05-10 08:33 UTC, ddadonJoin commented on packages/pubsub/src/Publisher.ts
> +    // Later we want to have only topic with specified schema and remove if block below
Can you add a TODO prefix in the comment to make the intent of removing it later clearer?

2023-05-10 08:33 UTC, ddadonJoin commented on packages/pubsub/src/TopicHandler.ts
> +  protected async getTopicType(): Promise<Type | undefined> {
I know this code predate our discussion from yesterday but we want to use the writer's schema over there, we can sync to align on how you can get it if you want :)

2023-05-10 08:33 UTC, ddadonJoin commented on packages/pubsub/src/Publisher.ts
> +    this.logger?.info(`PubSub: Message sent for topic: ${this.topicName}:`, { message, messageId })
Can you add the encoding scheme on the log to make it easier to search? Like `Avro-Message sent for topic...` and `Json-Message sent for topic...`

I could even give you the avro schema fingerprint if you want to log it too

2023-05-10 08:33 UTC, ddadonJoin commented on packages/pubsub/src/Subscriber.ts
> +      dataParsed = dataParser.replaceNullsWithUndefined(dataParsedWithNulls)
Nice :), would it be possible to include this as a custom deserializer like `DateType` and register it in `Type.forSchema()` below? It would encapsulate the logic even more

2023-05-10 08:33 UTC, ddadonJoin commented on packages/pubsub/src/Subscriber.ts
> +        dataParsed = this.parseData(message)
There is no `return` on line 158 so does that mean we will call this block every time we process a message? Also that mean we will call this.parseData() twice

2023-05-10 09:02 UTC, eugeneswave commented on packages/pubsub/src/DataParser.ts
> +        obj[key] = undefined;
Looks like we don't have this rule enable in the linter, but of course removing it here

2023-05-10 09:06 UTC, eugeneswave commented on packages/pubsub/src/Publisher.ts
> +        this.topic = this.client.topic(this.topic.name)
My logic was, because getTopicType works for the topic already received, and we need to update the topic first, and the execute getTopicType. Bus as we are having callback for getting topic metadata, maybe we will always have a fresh one, and we don't need to refresh topic. Checking this.

2023-05-10 09:43 UTC, eugeneswave commented on packages/pubsub/src/Publisher.ts
> +        this.topic = this.client.topic(this.topic.name)
yeah, it works, thanks for the comment! This allows us to skip refreshing the topic

2023-05-10 10:35 UTC, eugeneswave commented on packages/pubsub/src/Subscriber.ts
> +      dataParsed = dataParser.replaceNullsWithUndefined(dataParsedWithNulls)
Couldn't find any way to do this for the whole conversion. Yes it works for logical types, but not for the whole object, and every type.
https://github.com/mtth/avsc/wiki/API#typeforschemaschema-opts

2023-05-10 12:49 UTC, ddadonJoin commented on packages/pubsub/src/Publisher.ts
> +    this.logger?.info(`PubSub: Message sent for topic: ${this.topicName}:`, { message, messageId })
Yes good idea to get the schema version id in the logs

2023-05-10 13:09 UTC, kirpichenko commented on packages/pubsub/src/DataParser.ts
> +      } else if (typeof obj[key] === 'object') {
you need to be careful with this check, bc Date is also object

2023-05-10 13:15 UTC, kirpichenko commented on packages/pubsub/src/Publisher.ts
> +      this.avroType = await this.getTopicType()
I did not get it. I mean that instead of inheritance it's enough to use composition. You can keep the same class. I just don't see much sense here and prefer to avoid inheritance when possible

2023-05-10 13:18 UTC, kirpichenko commented on packages/pubsub/src/Subscriber.ts
> +  private readonly deadLetterSubscriptionName?: string
why did you move it? we usually keep all class properties on the top

2023-05-10 13:28 UTC, kirpichenko commented on packages/pubsub/src/Subscriber.ts
> +    return async (message: Message) => {
i think you can do smth like instead of callbackify, bc it looks extremely confusing 
```
return  (message: Message) => new Promise(async(resolve, reject) => {
   ... await ...
})
```

2023-05-10 19:46 UTC, eugeneswave commented on packages/pubsub/src/DataParser.ts
> +      } else if (typeof obj[key] === 'object') {
added additional check if object has a property

2023-05-10 19:46 UTC, eugeneswave commented on packages/pubsub/src/DataParser.ts
> +        (obj[key] as Record<string, unknown>[]).forEach(member => this.deepReplaceInObject(member))
added additional check if object has a property

2023-05-10 19:47 UTC, eugeneswave commented on packages/pubsub/src/Publisher.ts
> +      this.avroType = await this.getTopicType()
yeah, sorry for misunderstanding, I updated code base, it should look better now

2023-05-10 19:48 UTC, eugeneswave commented
I've addressed the issues except callbackify, will check it tomorrow, need more time, and also added 
https://joinsolutionsag.atlassian.net/browse/JOIN-31233

2023-05-12 09:41 UTC, closed without merging